# .github/workflows/deploy.yaml
name: Deploy GCP Cloud Function via WIF

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        token_format: access_token
        workload_identity_provider: "projects/31239933098/locations/global/workloadIdentityPools/github-pool/providers/github-provider2"
        service_account: "github-actions@guido-460817.iam.gserviceaccount.com"

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1

    - name: Deploy Cloud Function
      run: |
        gcloud functions deploy send_notification \
          --runtime python310 \
          --trigger-topic my-topic \
          --entry-point notify_email \
          --source . \
          --region=us-central1 \
          --set-env-vars "username=shashivadhan.gunti@gmail.com,password=your_app_password,sender=shashivadhan.gunti@gmail.com,SMTP=smtp.gmail.com,recipients=shashivadhan.gunti@gmail.com"
